select * from customer_shopping_behavior limit 20

--total generated by male vs female customers?
select gender, SUM(purchase_amount_usd) as revenue
from customer_shopping_behavior
group by gender

--which customer use discount but still spend more then purchase amount?
select customer_id, purchase_amount_usd
from customer_shopping_behavior 
where discount_applied = 'Yes' and purchase_amount_usd >= (select AVG(purchase_amount_usd) from customer_shopping_behavior)

--which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average_review_rating"
from customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;

--compare the average purchase amount between standard and express shipping
select shipping_type, 
AVG(purchase_amount_usd)
from customer_shopping_behavior
where shipping_type in ('Standard', 'Express')
group by shipping_type

--do sub customer spend more? compare avg spent and total revenue
select subscription_status, 
COUNT(customer_id) as customer_total,
ROUND(AVG(purchase_amount_usd), 2) as avg_spent,
ROUND(SUM(purchase_amount_usd), 2) as total_spent
from customer_shopping_behavior
group by subscription_status

-- which 5 products has the highest percentage of being purchased with discount?
select item_purchased,
ROUND(100 * SUM(case when discount_applied = 'Yes' then 1 else 0 end) / COUNT(*), 2) as discount_rate
from customer_shopping_behavior
group by item_purchased
order by discount_rate desc
limit 5;

--segment customers into new, returning, and loyal based on their spending
with customer_type as( 
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer_shopping_behavior
)

select customer_segment, count(*) as "Numbers of customers"
from customer_type
group by customer_segment

--what are the top 3 most purchased products in each category?
with item_counts as( 
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping_behavior
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Are customer who are repeat buyers(more then 5 previous purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status

--what is the revenue contribution of each age group?
select age_group, 
sum(purchase_amount_usd) as total_revenue
from customer_shopping_behavior
group by age_group order by total_revenue desc;